{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "80cc385d-baa3-4b06-8951-eeca7365c788",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "==========================================\n",
      "   Welcome to GradeBook Analyzer CLI\n",
      "==========================================\n",
      "\n",
      "OPTIONS:\n",
      "1. Enter Marks Manually\n",
      "2. Load from CSV\n",
      "3. Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Select an option (1-3):  1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "--- Manual Entry Mode ---\n",
      "Type 'done' as the name to finish.\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter Student Name:  John\n",
      "Enter mark for John:  23\n",
      "Enter Student Name:  Broo\n",
      "Enter mark for Broo:  43\n",
      "Enter Student Name:  snow\n",
      "Enter mark for snow:  33\n",
      "Enter Student Name:  done\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "========================================\n",
      "Name                 Mark       Grade\n",
      "----------------------------------------\n",
      "John                 23.0       F    \n",
      "Broo                 43.0       F    \n",
      "snow                 33.0       F    \n",
      "----------------------------------------\n",
      "\n",
      "--- Statistical Summary ---\n",
      "Average Mark : 33.00\n",
      "Median Mark  : 33.00\n",
      "Highest Mark : 43.0\n",
      "Lowest Mark  : 23.0\n",
      "\n",
      "--- Grade Distribution ---\n",
      "Grade A: 0 students\n",
      "Grade B: 0 students\n",
      "Grade C: 0 students\n",
      "Grade D: 0 students\n",
      "Grade F: 3 students\n",
      "\n",
      "--- Pass/Fail Status (Cutoff: 40) ---\n",
      "Passed (1): Broo\n",
      "Failed (2): John, snow\n",
      "\n",
      "OPTIONS:\n",
      "1. Enter Marks Manually\n",
      "2. Load from CSV\n",
      "3. Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Select an option (1-3):  2\n",
      "Enter CSV filename (e.g., students.csv):  students.csv\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: File 'students.csv' not found.\n",
      "No data found or entered. Returning to menu.\n",
      "\n",
      "OPTIONS:\n",
      "1. Enter Marks Manually\n",
      "2. Load from CSV\n",
      "3. Exit\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "Project: GradeBook Analyzer CLI\n",
    "Name: Gauri Sharma\n",
    "Roll no.: 2501730108\n",
    "Date: 25-11-2025\n",
    "Description: A tool to calculate student statistics, assign grades, \n",
    "             and generate formatted reports from manual input or CSV.\n",
    "\"\"\"\n",
    "\n",
    "import csv\n",
    "import os\n",
    "\n",
    "# --- Task 3: Statistical Analysis Functions ---\n",
    "def calculate_average(marks_dict):\n",
    "    \"\"\"Returns the arithmetic mean of marks.\"\"\"\n",
    "    if not marks_dict: return 0.0\n",
    "    return sum(marks_dict.values()) / len(marks_dict)\n",
    "\n",
    "def calculate_median(marks_dict):\n",
    "    \"\"\"Returns the median mark.\"\"\"\n",
    "    if not marks_dict: return 0.0\n",
    "    scores = sorted(marks_dict.values())\n",
    "    n = len(scores)\n",
    "    if n % 2 == 1:\n",
    "        return scores[n // 2]\n",
    "    else:\n",
    "        mid1 = scores[n // 2 - 1]\n",
    "        mid2 = scores[n // 2]\n",
    "        return (mid1 + mid2) / 2\n",
    "\n",
    "def find_max_score(marks_dict):\n",
    "    \"\"\"Returns the highest score.\"\"\"\n",
    "    if not marks_dict: return 0\n",
    "    return max(marks_dict.values())\n",
    "\n",
    "def find_min_score(marks_dict):\n",
    "    \"\"\"Returns the lowest score.\"\"\"\n",
    "    if not marks_dict: return 0\n",
    "    return min(marks_dict.values())\n",
    "\n",
    "# --- Task 4: Grade Logic ---\n",
    "def get_letter_grade(score):\n",
    "    \"\"\"Assigns letter grades based on the 90-80-70-60 scale.\"\"\"\n",
    "    if score >= 90: return 'A'\n",
    "    elif score >= 80: return 'B'\n",
    "    elif score >= 70: return 'C'\n",
    "    elif score >= 60: return 'D'\n",
    "    else: return 'F'\n",
    "\n",
    "# --- Input Handlers ---\n",
    "def input_manual():\n",
    "    \"\"\"Handles manual user entry of names and marks.\"\"\"\n",
    "    data = {}\n",
    "    print(\"\\n--- Manual Entry Mode ---\")\n",
    "    print(\"Type 'done' as the name to finish.\")\n",
    "    while True:\n",
    "        name = input(\"Enter Student Name: \").strip()\n",
    "        if name.lower() == 'done':\n",
    "            break\n",
    "        try:\n",
    "            score = float(input(f\"Enter mark for {name}: \"))\n",
    "            if 0 <= score <= 100:\n",
    "                data[name] = score\n",
    "            else:\n",
    "                print(\"Error: Marks must be between 0 and 100.\")\n",
    "        except ValueError:\n",
    "            print(\"Error: Please enter a valid number for the mark.\")\n",
    "    return data\n",
    "\n",
    "def input_csv():\n",
    "    \"\"\"Loads data from a CSV file (Format: Name,Mark).\"\"\"\n",
    "    data = {}\n",
    "    filename = input(\"Enter CSV filename (e.g., students.csv): \").strip()\n",
    "    \n",
    "    if not os.path.exists(filename):\n",
    "        print(f\"Error: File '{filename}' not found.\")\n",
    "        return {}\n",
    "\n",
    "    try:\n",
    "        with open(filename, mode='r') as file:\n",
    "            csv_reader = csv.reader(file)\n",
    "            next(csv_reader, None)  # Skip header if it exists\n",
    "            for row in csv_reader:\n",
    "                if len(row) >= 2:\n",
    "                    name = row[0].strip()\n",
    "                    try:\n",
    "                        score = float(row[1])\n",
    "                        data[name] = score\n",
    "                    except ValueError:\n",
    "                        continue # Skip bad data rows\n",
    "        print(f\"Successfully loaded {len(data)} records.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error reading file: {e}\")\n",
    "    \n",
    "    return data\n",
    "\n",
    "# --- Main Program Logic ---\n",
    "def main():\n",
    "    print(\"==========================================\")\n",
    "    print(\"   Welcome to GradeBook Analyzer CLI\")\n",
    "    print(\"==========================================\")\n",
    "\n",
    "    while True:\n",
    "        # Task 6: CLI Loop Menu\n",
    "        print(\"\\nOPTIONS:\")\n",
    "        print(\"1. Enter Marks Manually\")\n",
    "        print(\"2. Load from CSV\")\n",
    "        print(\"3. Exit\")\n",
    "        \n",
    "        choice = input(\"Select an option (1-3): \").strip()\n",
    "        \n",
    "        marks_data = {}\n",
    "\n",
    "        if choice == '1':\n",
    "            marks_data = input_manual()\n",
    "        elif choice == '2':\n",
    "            marks_data = input_csv()\n",
    "        elif choice == '3':\n",
    "            print(\"Exiting GradeBook Analyzer. Goodbye!\")\n",
    "            break\n",
    "        else:\n",
    "            print(\"Invalid selection. Try again.\")\n",
    "            continue\n",
    "\n",
    "        # If no data collected, restart loop\n",
    "        if not marks_data:\n",
    "            print(\"No data found or entered. Returning to menu.\")\n",
    "            continue\n",
    "\n",
    "        # --- ANALYSIS PHASE ---\n",
    "        \n",
    "        # 1. Statistics\n",
    "        avg = calculate_average(marks_data)\n",
    "        med = calculate_median(marks_data)\n",
    "        highest = find_max_score(marks_data)\n",
    "        lowest = find_min_score(marks_data)\n",
    "\n",
    "        # 2. Grade Assignment & Distribution\n",
    "        grades_dict = {}\n",
    "        grade_counts = {'A': 0, 'B': 0, 'C': 0, 'D': 0, 'F': 0}\n",
    "\n",
    "        for name, score in marks_data.items():\n",
    "            grade = get_letter_grade(score)\n",
    "            grades_dict[name] = grade\n",
    "            grade_counts[grade] += 1\n",
    "\n",
    "        # 3. Task 5: List Comprehensions (Pass >= 40, Fail < 40)\n",
    "        passed = [name for name, score in marks_data.items() if score >= 40]\n",
    "        failed = [name for name, score in marks_data.items() if score < 40]\n",
    "\n",
    "        # --- REPORTING PHASE ---\n",
    "        print(\"\\n\" + \"=\"*40)\n",
    "        print(f\"{'Name':<20} {'Mark':<10} {'Grade':<5}\")\n",
    "        print(\"-\" * 40)\n",
    "        \n",
    "        for name, score in marks_data.items():\n",
    "            # Task 6: Formatted Table using f-strings\n",
    "            print(f\"{name:<20} {score:<10.1f} {grades_dict[name]:<5}\")\n",
    "        print(\"-\" * 40)\n",
    "\n",
    "        print(\"\\n--- Statistical Summary ---\")\n",
    "        print(f\"Average Mark : {avg:.2f}\")\n",
    "        print(f\"Median Mark  : {med:.2f}\")\n",
    "        print(f\"Highest Mark : {highest}\")\n",
    "        print(f\"Lowest Mark  : {lowest}\")\n",
    "\n",
    "        print(\"\\n--- Grade Distribution ---\")\n",
    "        for g, count in grade_counts.items():\n",
    "            print(f\"Grade {g}: {count} students\")\n",
    "\n",
    "        print(\"\\n--- Pass/Fail Status (Cutoff: 40) ---\")\n",
    "        print(f\"Passed ({len(passed)}): {', '.join(passed)}\")\n",
    "        print(f\"Failed ({len(failed)}): {', '.join(failed)}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "998e4e53-a981-466d-bfdb-a83ff126aef8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
